### ISSUE TITLE
GridItem没有类型提示

### ISSUE THREAD

**Issue by MeetinaXD** [xhlife/vue3-grid-layout#8]
如题，GridLayout.vue.d.ts有Props等类型；而GridItem不知道什么原因，d.ts中只有一个unknown类型的Component

这在TSX下使用会非常不友好，开发大哥有空可以看看是什么问题！

**Comment by xhlife** [comment]
已更新d.ts文件

**Comment by MeetinaXD** [comment]
已经解决我的问题，感谢您的工作！
